### PR TITLE
Removes Transports and Implements HTTP Logger Backend

### LINKED ISSUE #106: Provide different backends instead of using transports
Based on conversations with the community and our own needs at Timber, it is best for us to separate out the logging mechanism into proper Logger application backends.

### LINKED ISSUE #109: Update installer to work with new backends methodology

### PR DESCRIPTION
**Pull request by DavidAntaramian**
This is a major change to the way that our library operates and is based on feedback from the community. In version suites 0.x and 1.x we created a singular Logger backend that then operated through a selected transport. While this solved the issue of redundant code, it limited and restricted the usability of Timber in various ways. With versions in 2.x and beyond, we will supply multiple backends depending on the user's needs.

First and foremost, the IODevice transport is gone and it is _not_ being replaced by a unique Timber backend. In many ways, it replicated the `:console` backend provided with Elixir's Logger application; indeed that's what the code was based on. However, this proved to be brittle because our code would not benefit from any changes in the `:console` backend as users upgraded their Elixir versions.

Furthermore, James Fish pointed out that there is a feature of the `:console` logger that allows the output to be formatted by a custom function. This has been available in every major release of the `:console` backend but has been undocumented until Elixir 1.5 (current master/unstable). Timber now prefers utilizing `:console` as its backend for writing to STDOUT and formatting the output via the `Timber.Formatter.format/4` function. This change was effective in PR #108.

Second, this removes the HTTP transport and adds the `Timber.LoggerBackends.HTTP` backend. This backend allows

One of the major improvements this provides is that users can opt to use both the `:console` backend with the custom Timber formatter as well as the `Timber.LoggerBackends.HTTP` backend (and as many other backends as they would like), and it will not affect the behavior of Timber in any manner. In this way, users that want both STDOUT logging for local reference as well as logging to Timber over HTTP can easily achieve this _and_ have their Timber context present and formatted in both.

Closes #106 
Closes #109

### CODE REVIEW

**Comment by binarylogic** [comment]
Nice work. I'd also update the `Install.ConfigFile` module to use these new changes.

**Comment by DavidAntaramian** [comment]
Yeah that's the next bit I need to figure out :)

**Comment by binarylogic** [comment]
And...just realized the `WIP` tag.

**Comment by binarylogic** [comment]
This should be the only place you need to modify: https://github.com/timberio/timber-elixir/blob/master/lib/mix/tasks/timber/install/config_file.ex#L47-L52. And the function all to `timber_portion`.

**Comment by binarylogic** [comment]
Also, I just remembered, we'll need to update this as well:

https://github.com/timberio/timber-io/blob/master/_docs/elixir/installation/manual-installation.md

**Pull request merged**
